services:
  mcp-server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - timescaledb
    environment:
      - REDIS_HOST=redis
      - PG_HOST=timescaledb
    volumes:
      - ./app:/app

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mcpdb
      POSTGRES_USER: mcpuser
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data

volumes:
  timescale_data:
